#!groovy

def talent(){
    echo "talent factory"
}

pipeline {
    agent any
    
    stages{
        stage("test"){
            steps{
                echo "hello world"
            }
        }
        stage("nombre"){
            steps{
                echo "${name}"
            }
        }
        stage("talent"){
            steps{
                talent()
            }
        }
    }
}